// <auto-generated />
namespace TechnicalAssignment.DataAccess
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class TechnicalAssignment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TechnicalAssignment));
        
        string IMigrationMetadata.Id
        {
            get { return "201911210725563_TechnicalAssignment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
